sudo: required
language: python
os:
- linux
dist: trusty
python:
- '2.7'
before_install:
- pip install --upgrade pip
- sudo add-apt-repository ppa:ubuntu-wine/ppa -y
- sudo apt-get update -qq
- sudo apt-get install -qq wine
- wget https://www.python.org/ftp/python/2.7.9/python-2.7.9.amd64.msi --output-document=python.msi
- wine msiexec /i python.msi /qn
- wget https://files.pythonhosted.org/packages/83/cc/2e39fa39b804f7b6e768a37657d75eb14cd917d1f43f376dad9f7c366ccf/pywin32-224-cp27-cp27m-win_amd64.whl
  --output-document=pywin32-224-cp27-none-win_amd64.whl
- wine c:\\Python27\\python.exe -m pip install pywin32-224-cp27-none-win_amd64.whl
- wine c:\\Python27\\python.exe -m pip install pyasn1
- wine c:\\Python27\\python.exe -m pip install enum34
- wine c:\\Python27\\python.exe -m pip install https://github.com/AlessandroZ/pypykatz/archive/master.zip
- wine c:\\Python27\\python.exe -m pip install pyinstaller
- wine c:\\Python27\\Scripts\\pyinstaller --noconsole --onefile Windows/lazagne.spec
script:
- wine Z:\\home\\travis\\build\\welikechips\\LaZagne\\dist\\laZagne.exe all
before_deploy:
- tar -zcvf lazagne.tar.gz dist/lazagne.exe
deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  api_key:
    secure: UT94ZbdZGEI0mBiUSaD+CBDBRd8rwBr2CKCKioanr1tlo8Mb0PoS9FwGojTOi/Zz1dFmu7aLdZfw9wjmn3VQKT8Rbe50zFni+ocbXs9//2+KwXJXLKhDb3ijYdNQhdlP4TMPNyJmGJ9ZoFcHro+yEY8y1031PX44A/Ovs1/J7WQuWptxaXN3c1iPEwBjoIPcKnPhB6ocG4mVZgqV2FXyOgPpeTodtAFSaj7ymdzBIxOKvAnyOoZJDvA8i6yamHyzATWO563q9o9m4aru51fl7Hzsoxxt0MwaBKu1HnDhjLuYF2hjIdOD3ed9G4Kb+5FhOr6O+0hngRt6z2SWPHXrZ5VjGb+1c7qnxNuZFVltefLbhFK3qA+8ypOY69iMABF4shWiWtHWdidZpqtJvncuh4EOcpuEe4+ghfROU/hNs4caD9G0QYoyaZCEwqlmzF/zQpl77Bm0ZbTJc4kgy3Ew0/zHIPSJwQToz2Bts0X154NPa6Hlgq8OZJpzs6X6ZRtt2arvEK0ZPqA8RJc3b5LEd8JjuRLdGNkeiHP27NxcpNwGXik7Gjs4B8x6vPcaYC0balyjOSliMC7RK/4bC0vWH1Oopa2XntfHy5p1tsMAXV1AvVCTotTtglQtg8j7o8jCBwo4UHxdy0TJ23+yqpr0yUL+7AnJVIggYB1TjcOA2T8=
  file: 
    - dist/lazagne.exe
    - lazagne.tar.gz    
  on:
    tags: true
    all_branches: true
    repo: welikechips/LaZagne
